framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'rajhiaziz2@gmail.com'
        headers:
            From: 'E-Sport Platform <rajhiaziz2@gmail.com>'
